# Generated by Django 3.0.8 on 2020-07-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aboutuser',
            field=models.CharField(default='Add Profile Description', max_length=200),
        ),
    ]
