# Generated by Django 3.0.8 on 2020-07-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_aboutuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='aboutuser',
            new_name='description',
        ),
    ]
