# Generated by Django 3.0.8 on 2020-07-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200710_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
