# Generated by Django 3.0.8 on 2020-07-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstSkill',
            field=models.CharField(default='Add First Skill', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='secondSkill',
            field=models.CharField(default='Add Second Skill', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='thirdSkill',
            field=models.CharField(default='Add Third Skill', max_length=200),
        ),
    ]
