# Generated by Django 3.0.4 on 2020-07-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0002_comment_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='Add Post Summary'),
        ),
    ]
