# Generated by Django 3.0.4 on 2020-07-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0010_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='name',
            new_name='devicename',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensorname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
