# Generated by Django 3.0.4 on 2020-07-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0011_auto_20200725_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='pub_date',
            field=models.DateTimeField(default=0, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
