# Generated by Django 3.0.4 on 2020-07-26 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0012_sensor_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='pub_date',
        ),
    ]
