# Generated by Django 3.0.4 on 2020-07-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0013_remove_sensor_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='pub_date',
            field=models.DateTimeField(default=1994, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
