# Generated by Django 3.0.4 on 2020-07-26 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0015_auto_20200726_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='pub_date',
        ),
    ]
